### ISSUE TITLE
shallow_net_in_keras.ipynb 

### ISSUE THREAD

**Issue by raokrutarth** [the-deep-learners/TensorFlow-LiveLessons#14]
The dimension of the dataset has changed. You may want to update the notebook if you are still maintaining it. Just came upon this while going through the Safaribooks online course.

**Comment by jonkrohn** [comment]
Thanks for this, @raokrutarth. It's greatly appreciated. 

Because [my installation instructions](https://github.com/the-deep-learners/TensorFlow-LiveLessons/tree/master/installation) recommend using a Docker container, the libraries are fixed at the versions indicated in my [Docker file](https://github.com/the-deep-learners/TensorFlow-LiveLessons/blob/master/Dockerfile) and so this isn't an issue. 

That said, I'm curious about this for future materials that I develop with newer libraries. Can you please describe the issue in more detail, e.g., in what dimension has the dataset changed?
