### ISSUE TITLE
Errors at docker run to start the built image

### ISSUE THREAD

**Issue by oonisim** [the-deep-learners/TensorFlow-LiveLessons#33]
# Environment
OS VERSION="18.04.4 LTS (Bionic Beaver)"
Docker version 19.03.8, build afacb8b7f0

# Problem
Had multiple errors when run the docker run command. It seems jupyter notebook version related.
```
sudo docker run -v $(pwd):/home/jovyan/work -it --rm -p 8888:8888 tensorflow-ll-stack
```

## ImportError: No module named notebook.notebookapp
As in https://stackoverflow.com/questions/31401890/, adding the line in Dockerfile and fixed the issue.
```
RUN pip install jupyter
```

## importerror : cannot import name 'secure_write' while updating python in conda evironment

As in https://stackoverflow.com/questions/58792782, adding the line in Dockerfile and fixed the issue.
```
RUN pip install --upgrade jupyter_client
```

## socket.gaierror: [Errno -2] Name or service not known
As in https://stackoverflow.com/questions/52706238, Replaced from "c.NotebookApp.ip = '*'" to "c.NotebookApp.ip = '0.0.0.0'" in jupyter_notebook_config.py, and copied the file by adding the line in the Dockerfile, which stopped the error.
```
COPY installation/docker-stack-scripts/jupyter_notebook_config.py /home/jovyan/
```

However, not sure these are the correct solutions. Please review.

---

# Explanation of the startup
It looks the [tini](https://github.com/krallin/tini) is started as the PID 1 and doing bootstrapping. As Dockerfile has no entry point nor CMD specified, I suppose there is a configuration file somewhere which is invoking /home/jovyan/work/installation/docker-stack-scripts/start.sh in the mounted volume. Please explain how this bootstrapping has been configured inside the docker.

# Python 3
Please advise if there is a plan to update to Python 3.

**Comment by jonkrohn** [comment]
Hey there @oonisim ! Thanks for reporting these issues. 

It sounds like all of them may be resolved by using [the latest edition of these videos and accompanying Jupyter notebooks](https://github.com/jonkrohn/DLTFpT). Would you mind checking that out? The latest edition contains all of the content from the earlier edition, but quite a bit more. 

I'm going to close this issue for now since I'm not planning on updating this older repo anymore if I can avoid it.
